source 'https://rubygems.org'
ruby '2.1.0'

gem 'ruby-opencv', '~> 0.0.12', require: 'opencv'
gem 'mini_magick'
gem 'sinatra'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'cocaine'
gem 'colorscore'
gem 'puma'